packages:
    - 'apps/*'
    - 'packages/*'

catalogs:
    v1:
        vue: 3.5.13
        vue-router: 4.5.0
        vue-tsc: 2.2.0
        vite: 6.0.5

        hono: 4.6.16

        typescript: 5.6.2

        '@vitejs/plugin-vue': 5.2.1
        '@vue/tsconfig': 0.7.0

        '@types/node': 22.10.5
